###############################################################################
# порядковый номер
#   id предмета (можно даже из модов)
#   шанс срабатывания. чем больше, тем ниже шанс. 1 - 100%, 2 - 50% и так далее
#   команды, обрабатываемые консолью. можете включить фантазию*
###############################################################################

# * если команда начинается с NARRATE, всё после неё будет отправлено игроку в чат. Например:
# NARRATE §aПриятного аппетита!
# Тэг {PLAYER} возвращает ник игрока
#
#
# Пример конфигурации:
#
# 1:
#  - APPLE
#  - 1
#  - kill {PLAYER}
#  - NARRATE §cПохоже, это яблоко было отравлено.

debug: true

1:
  - CARROT_ITEM
  - 2
  - effect {PLAYER} minecraft:speed 10 1
  - NARRATE §aМорковь придала вам сил!